name: Continuous Integration
on:
  push:
    branches:
      - main
      - actions-*
    tags:
      - v*
  pull_request:
    branches-ignore:
      - actions-*
  workflow_dispatch:

jobs:
  specs:
    name: ruby-${{ matrix.ruby }} ${{ matrix.appraisal }}
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "ruby"
            standardrb: true
            yard: true
          - ruby: "4.0"
            appraisal: "redis_6"
          - ruby: "3.4"
            appraisal: "redis_5"
          - ruby: "2.7"
            appraisal: "redis_4.5"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Ruby CI
        uses: bdurand/github-actions/ruby-ci@b7560883d5f8557f5d69fe8bd82721bbb5ed76df # v1.0.4
        with:
          ruby: ${{ matrix.ruby }}
          appraisal: ${{ matrix.appraisal }}
          bundler: ${{ matrix.bundler }}
          standardrb: ${{ matrix.standardrb }}
          yard: ${{ matrix.yard }}
          frozen_strings: ${{ matrix.frozen_strings }}
