name: Continuous Integration
on:
  push:
    branches:
      - master
      - actions-*
    tags:
      - v*
  pull_request:
env:
  BUNDLE_CLEAN: "true"
  BUNDLE_PATH: vendor/bundle
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3
  CC_TEST_REPORTER_ID: 95bb5a1721abab90f03e8b3356ee35acf427a7748b9d3bbad70a3bad62ea860a
jobs:
  specs:
    name: run tests
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: setup bundler
        run: |
          bundle update
      - name: specs
        run:  bundle exec rake spec || ls -l || ls -l coverage/
      - name: code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        with:
          debug: true
      - name: standardrb
        run:  bundle exec rake standard
